lang: en
title: "Aniket Pramanik"
url: "https://anikpram.github.io"   # <-- use your actual GitHub username here
baseurl: ""

remote_theme: alshedivat/al-folio@v0.14.6


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-scholar
  - jekyll-toc

collections:
  posts:
    output: true
    permalink: /blog/:title/

  pages:
    output: true
    permalink: /:path/

paginate: 0
paginate_path: "/blog/page:num/"
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge

max_width: 930px


scholar:
  source: _bibliography
  bibliography: papers.bib
  style: apa           # or ieee, acm, etc. (optional)
  locale: en

# Theme settings
navbar_fixed: true
footer_fixed: true
show_navbar: true 
show_social_icons: true
enable_darkmode: true
enable_google_analytics: false # set to true and add your GA ID
