lang: en
#title: "Aniket Pramanik"
url: "https://anikpram.github.io"   # <-- use your actual GitHub username here
baseurl: ""

remote_theme: alshedivat/al-folio@v0.14.6


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-scholar
  - jekyll-toc
  - jekyll-github-metadata
  - jekyll-katex

collections:
  posts:
    output: true
    permalink: /blog/:title/

  pages:
    output: true
    permalink: /:path/

paginate: 0
paginate_path: "/blog/page:num/"
permalink: pretty


# Enable MathJax
#enable_math: true

#markdown: kramdown
#kramdown:
#  input: GFM
#  math_engine: mathjax


max_width: 930px


scholar:
  source: _bibliography
  bibliography: papers.bib
  style: apa           # or ieee, acm, etc. (optional)
  locale: en
  last_name: "Pramanik"
  first_name: "Aniket"
  sort_by: year
  order: descending   # newest first

# Theme settings
navbar_fixed: true
footer_fixed: true
show_navbar: true 
show_social_icons: true
enable_darkmode: true
enable_google_analytics: false # set to true and add your GA ID


# replace with your actual repo slug and username
repository: anikpram/anikpram.github.io
github: 
  username: anikpram
  sort_by: stars
  limit: 12



#plugins:
#  - jekyll-github-metadata
  # (keep your other plugins)


  # repo color theme
repo_theme_light: default       # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_theme_dark: dark           # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_trophies:
  enabled: true
  theme_light: flat    # https://github.com/ryo-ma/github-profile-trophy
  theme_dark: gitdimmed  # https://github.com/ryo-ma/github-profile-trophy